FROM debian:stable
LABEL maintainer="jm9357481@gmail.com"

RUN apt update -y && apt upgrade -y && apt install -y python3 python3-pip
WORKDIR /app

COPY . /app
RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3" ]
CMD [ "app.py" ]
