version: 1
datastore:
  user: "root"
  password: ""
  hostname: "acit-3855-kafka.jake-m-commits.link"
  port: 3306
  db: "events"
events:
  hostname: "acit-3855-kafka.jake-m-commits.link"
  port: 9092
  topic: "events"
